services:
  - type: web
    name: shitizosintbot
    env: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME

        sync: false
